In [8]:
import numpy as np
import scipy as sp
from scipy import ndimage

In [32]:
#Need to learn how to rotate array

matr_1= [[0, 1, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 1, 0]]

matr_2= [[0, 0, 1, 0, 0, 0],
        [0, 1, 1, 1, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 1, 1],
        [0, 0, 0, 0, 1, 0]]

print("Rotation by 45 degrees")
print(ndimage.rotate(matr_1, 45, reshape=False))

print("Rotation by 55 degrees")
print(ndimage.rotate(matr_2, 55, reshape=False))



Rotation by 45 degrees
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 0 0 1 1]
 [1 1 0 0 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Rotation by 45
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 1 1 0 1 1]
 [0 1 1 0 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
